Music_platform_desc: 音乐平台：netease,qq,kugou,kuwo,soda,spotify,apple,ayna,potplayer,foobar,lx,huahua,musicfree,bq,aimp,youtube,miebo,yesplay,cider
Music_platform: netease
GetMusicStatus_position_desc: 获取音乐状态程序位置
GetMusicStatus_position: C:/Users/sanmu214/myfolder/mysoftware/now_playing_music_getter/GetMusicStatus.exe
Cache_len_desc: 3d图片缓存长度
Cache_len: 10
Cover_intensity_desc: 景深
Cover_intensity: -1.5
Background_intensity: 5
Word_intensity: -1.5
Background_blur_desc: 背景
Background_blur: 20
Background_dark_percent: 0.3
Max_title_width_percent_desc: 标题
Max_title_width_percent: 0.9
Title_y_position_percent: 0.6
Artist_y_position_percent_offset_from_title: 0.08
Has_cover_blur_border_desc: 封面
Has_cover_blur_border: true
Cover_size_percent: 0.9
Cover_y_position_percent: 0.05
Control_y_position_percent_desc: 控制按钮
Control_y_position_percent: 0.93
Font_style_desc: 字体
Font_style: msyh.ttc
version: 1.0.1
lang_type: auto
